DROP DATABASE IF EXISTS azienda;
CREATE DATABASE IF NOT EXISTS Azienda;
USE Azienda;


CREATE TABLE Cliente(
	ClienteID INTEGER PRIMARY KEY AUTO_INCREMENT,
	Nome VARCHAR(100),
	Citta VARCHAR(150)
);

CREATE TABLE Magazzino(
    ArticoloID INTEGER PRIMARY KEY AUTO_INCREMENT,
    nomeArticolo VARCHAR(255),
    costo FLOAT
);

CREATE TABLE Ordini(
    OrdineID INTEGER PRIMARY KEY AUTO_INCREMENT,
    DataOrdine VARCHAR(100),
    Quantita INTEGER,
    Importo FLOAT,
    ClienteID INTEGER,
	ArticoloID INTEGER,
	FOREIGN KEY (ClienteID) REFERENCES Cliente (ClienteID) ON DELETE CASCADE ON UPDATE CASCADE,
    FOREIGN KEY (ArticoloID) REFERENCES Magazzino (ArticoloID) ON DELETE CASCADE ON UPDATE CASCADE
);